[package]
name = "fifotax"
version = "0.1.0"
authors = ["Kenneth Blomqvist <kekeblom@gmail.com>"]

[dependencies]
csv = "1.0.0-beta.5"
chrono = { version = "0.4", features = ["serde"] }
serde = "1"
serde_derive = "1"
clap = "2.29.0"
